### ISSUE TITLE
Explain exactly what you mean by Unable to recognize VOICES.

### ISSUE THREAD

**Issue by k896951** [KamiCreed/pyaivchat#1]
Hello!
I am a developer of AssistantSeika.
I have read the troubleshooting description in README.dm.
Can you please explain exactly what you mean by "Unable to recognize VOICES"?
My assumption was that it only failed to assign a cid, but that the recognition itself would succeed.

**Comment by KamiCreed** [comment]
Hello.

Ok. Well, when I scanned the product instance for A.I. Voice with only the Kotonoha English voices installed, the "Avators" list did not populate and it said some kind of internal error happened. AssistantSeika seemed to find the A.I. Voice window, since there was movement there, but the Avators tab came up blank.

I have only tried it twice and it happened both times. It seemed to be fixed when I downloaded the trial version for one of other voices namely Yuitsuka Yukari's voice.

**Comment by k896951** [comment]
Thank you for your explanation.

I understood that the content was an explanation that "on the A.I.VOICE editor, the character graphics of each voice switched in order, but the Avators tab was empty."

The reason is that the GUI structure of the A.I.VOICE editor is not what AssistantSeika expects.
Specifically, it cannot be processed because the necessary elements are not included in the VOICES name list of the GUI. That is why the VOICES name cannot be displayed.

Fortunately, however, it turned out that by applying the method you presented, it seems possible to have the same GUI structure as the Japanese version of the A.I.VOICE editor.

I'll post the method you presented on the distribution site as well.

Thank you for telling me.

p.s.
There are similar cases even in the same Japanese version.
For example, in VOICEROID2, there may be an instance with a GUI structure that cannot be analyzed by AssistantSeika even though it is the same version.
Perhaps this happens due to the combination of installed VOICES.

**Comment by KamiCreed** [comment]
@k896951

I noticed on your website you said you can't fix this problem due to not having the overseas (English) version, but you can download the trial version on aivoice.jp to test it, since I had the same problem when I was trying it before I bought it. You'll probably have to uninstall your previous A.I. VOICE Editor installation beforehand or change the install location, though. Also, you'll only have 14 days in the trial to fix it but hopefully it won't take that long. Regardless, thanks for reaching out to me about this issue.

**Comment by k896951** [comment]
Thank you for contacting.

When I download it from the URL you show, it is the Japanese version. It is not the overseas version.

Actually, I am using the trial version when supporting A.I.VOICE for the first time with AssistantSeika. It was obtained from this URL. The GUI element search logic is built based on this trial version, and at least in the Japanese version, it works with the same logic up to the latest Ver1.2.1.0.

Therefore, it is necessary to investigate in the overseas version (English version).
* But I don't have an overseas version ...
